# Program:
NAME := megaphone

# Necessities
CXX := c++
CXXFLAGS := -std=c++98 -Wall -Wextra -Werror -pedantic

# Targets
SRC := megaphone.cpp

# Rules
all: $(SRC)
	$(CXX) -o $(NAME) $(CXXFLAGS) $(SRC)